[versions]
agp = "8.13.1"
kotlin = "2.2.21"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }
androidX-compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2025.11.00" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
material = { group = "com.google.android.material", name = "material", version = "1.13.0" }
androidX-compose-material3 = { group = "androidx.compose.material3", name= "material3" }
androidX-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidX-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidX-activity-compose = { group = "androidx.activity", name="activity-compose" }
androidX-activity-ktx = { group = "androidx.activity", name="activity-ktx" }
androidX-compose-ui  = { group = "androidx.compose.ui", name = "ui" }
androidX-compose-animation  = { group = "androidx.compose.animation", name = "animation" }
androidX-compose-foundation  = { group = "androidx.compose.foundation", name = "foundation" }
androidX-splashscreen = { group = "androidx.core", name = "core-splashscreen", version = "1.2.0" }

junit = { group = "junit", name = "junit", version = "4.13.2" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.3.0" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.7.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

